/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DeIndexRouteImport } from './routes/de/index'
import { Route as DeImpressumRouteImport } from './routes/de/impressum'
import { Route as DeDatenschutzRouteImport } from './routes/de/datenschutz'

const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeIndexRoute = DeIndexRouteImport.update({
  id: '/de/',
  path: '/de/',
  getParentRoute: () => rootRouteImport,
} as any)
const DeImpressumRoute = DeImpressumRouteImport.update({
  id: '/de/impressum',
  path: '/de/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const DeDatenschutzRoute = DeDatenschutzRouteImport.update({
  id: '/de/datenschutz',
  path: '/de/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/de/datenschutz': typeof DeDatenschutzRoute
  '/de/impressum': typeof DeImpressumRoute
  '/de/': typeof DeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/de/datenschutz': typeof DeDatenschutzRoute
  '/de/impressum': typeof DeImpressumRoute
  '/de': typeof DeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/de/datenschutz': typeof DeDatenschutzRoute
  '/de/impressum': typeof DeImpressumRoute
  '/de/': typeof DeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/de/datenschutz'
    | '/de/impressum'
    | '/de/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/de/datenschutz'
    | '/de/impressum'
    | '/de'
  id:
    | '__root__'
    | '/'
    | '/datenschutz'
    | '/impressum'
    | '/de/datenschutz'
    | '/de/impressum'
    | '/de/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  DeDatenschutzRoute: typeof DeDatenschutzRoute
  DeImpressumRoute: typeof DeImpressumRoute
  DeIndexRoute: typeof DeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/': {
      id: '/de/'
      path: '/de'
      fullPath: '/de/'
      preLoaderRoute: typeof DeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/impressum': {
      id: '/de/impressum'
      path: '/de/impressum'
      fullPath: '/de/impressum'
      preLoaderRoute: typeof DeImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/de/datenschutz': {
      id: '/de/datenschutz'
      path: '/de/datenschutz'
      fullPath: '/de/datenschutz'
      preLoaderRoute: typeof DeDatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  DeDatenschutzRoute: DeDatenschutzRoute,
  DeImpressumRoute: DeImpressumRoute,
  DeIndexRoute: DeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
